import {Clock} from './Clock.js';import {EventBus} from './EventBus.js';import {StateMachine} from './StateMachine.js';import {Plant} from '../simulation/Plant.js';import {InspectionSimulation} from '../simulation/InspectionSimulation.js';import {FaultInjection} from '../simulation/FaultInjection.js';import {EventLogger} from '../evidence/EventLogger.js';import {encode,LineParser} from '../protocol/Protocol.js';
export class DigitalTwin {
 constructor(data){this.data=data;this.clock=new Clock();this.bus=new EventBus();this.logger=new EventLogger();this.plant=new Plant();this.fw=new StateMachine(this);this.pi=new InspectionSimulation(this);this.faults=new FaultInjection(this,data.faults);this.decision={};this.result=null;this.lastHB=0;this.cause=null;this.demo=null;this.parser=new LineParser(m=>this.fw.receive(m),reason=>{this.event('PROTOCOL_ERROR',reason);this.protocol('PICO',{v:1,boot:this.fw.boot,cycle:this.fw.cycle,cmd:'NACK',reason});});this.event('BOOT','Outputs seguros; cadena física abstracta con BLOCKERs abiertos');this.protocol('PICO',{v:1,cmd:'HELLO',boot:this.fw.boot,cycle:0,state:'BOOT_SAFE'});}
 event(type,detail,extra={}){const row=this.logger.append({t_ms:this.clock.now,boot:this.fw?.boot,cycle:this.fw?.cycle,state:this.fw?.state,type,detail,...extra,sensors:this.plant.sensors(),actuators:{nEN:this.plant.nEN,rotor_angle:this.plant.rotorAngle,gate_angle:this.plant.gateAngle},pi:this.pi?.stage??'BOOT',power:{logic:true,actuators:this.plant.power,servo_v:this.plant.servoSupply}});this.cause={cause:detail,signal:type,decision:this.fw?.state,actuation:this.plant.rotorCommand?'NEMA':this.plant.gateCommand!==null?'MG996R':'QUIETO',confirmation:row.sensors,evidence:`evento ${this.logger.events.length}, ${row.t_ms} ms SIMULATED`};this.bus.emit(type,row);return row;}
 protocol(direction,msg,options={}){const raw=encode(msg);const row={direction,raw,message:msg,t_ms:this.clock.now,boot:msg.boot,cycle:msg.cycle,request:msg.request??null,crc:raw.slice(-5,-1),source:'SIMULATION',lost:!!options.lost};this.logger.protocol.push(row);this.event('PROTOCOL',`${direction} ${msg.cmd}`,{message:msg,raw,lost:!!options.lost});return raw;}
 sendSort(msg,{corrupt=false}={}){let raw=this.protocol('PI',msg);if(corrupt)raw=raw.slice(0,-5)+'0000\n';this.parser.feed(raw,this.clock.now);}
 action(kind,value){const p=this.plant;if(kind==='rearm')return this.fw.rearm();if(kind==='lid'){p.lid=!!value;if(!p.lid)p.power=false;this.event('LID',p.lid?'CLOSED':'OPEN');return true;}if(kind==='door'){p.door=!!value;if(!p.door)p.power=false;this.event('DOOR',p.door?'CLOSED':'OPEN');return true;}if(kind==='estop'){p.estop=!!value;if(value)p.power=false;this.event('E_STOP',value?'PRESSED':'RELEASED');return true;}if(kind==='load'){if(this.fw.state!=='READY')return false;p.load(value);this.event('OBJECT_LOADED','Objeto simulado sobre bandeja');return true;}if(kind==='inspect_clear'){if(!['BOOT_SAFE','FAULT','REVIEW'].includes(this.fw.state))return false;p.clearManually();this.event('MANUAL_INSPECTION','Retiro manual SIMULADO, guía vacía y hoja cerrada; no es movimiento automático');return true;}return false;}
 startDemo(kind){if(this.fw.state!=='READY')return false;this.result=null;this.decision={};this.action('lid',false);this.demo={kind,started:this.clock.now,loaded:false,closed:false};return true;}
 rebootPico(){const old=this.fw.boot;this.plant.cut();this.fw=new StateMachine(this);this.pi=new InspectionSimulation(this);this.demo=null;this.event('PICO_RESET',`Boot anterior ${old} invalidado; operación sin conciliar`);this.protocol('PICO',{v:1,cmd:'HELLO',boot:this.fw.boot,cycle:0,state:'BOOT_SAFE'});}
 rebootPi(afterFall=false){this.plant.cut();this.pi=new InspectionSimulation(this);this.demo=null;if(afterFall||this.logger.journal.pending)this.fw.review('PENDING_PHYSICAL_RECONCILIATION');else this.fw.fault('PI_RESTART');this.event('PI_RESET','Journal pendiente no se convierte en éxito ni en nueva orden');}
 tick(dt=20){this.clock.advance(dt);const now=this.clock.now;
  if(this.demo){const age=now-this.demo.started;if(age>=250&&!this.demo.loaded){this.action('load',this.demo.kind);this.demo.loaded=true;}if(age>=600&&!this.demo.closed){this.action('lid',true);this.demo.closed=true;this.demo=null;}}
  this.faults.tick();this.plant.update(dt,now);
  if(this.plant.usb&&!this.plant.piFrozen&&now-this.lastHB>=200){this.lastHB=now;this.fw.receive({v:1,cmd:'HEARTBEAT',boot:this.fw.boot});this.logger.protocol.push({direction:'PI',raw:encode({v:1,cmd:'HEARTBEAT',boot:this.fw.boot}),message:{v:1,cmd:'HEARTBEAT',boot:this.fw.boot},t_ms:now,source:'SIMULATION'});}
  this.parser.tick(now);this.fw.tick();if(this.fw.state==='WAIT_DECISION')this.pi.tick(now);
 }
 stepEvent(){const count=this.logger.events.length;for(let i=0;i<300;i++){this.tick();if(this.logger.events.length>count)return;}this.event('IDLE','Sin transición; esperando estímulo físico simulado');}
 gpio(){const p=this.plant;return this.data.pinout.map(x=>{let v='INPUT';const g=x.gpio;if(g===0)v=p.stepRate>0?'PULSE':'LOW';if(g===1)v=p.dir?'HIGH':'LOW';if(g===2)v=p.nEN?'HIGH / DISABLED':'LOW';if(g===3)v=p.power&&p.gateCommand!==null?'PWM':'DISABLED';if(g===4||g===5)v='I2C';if(g>=6&&g<=9)v=p.tof.xshut[g-6]?'HIGH-Z':'LOW';if(g===10)v='PULSE INPUT';if(g===11)v='PULSE';const ins={12:p.lid,13:p.gateClosed,14:p.gateOpen,15:false,16:p.reeds[0],17:p.reeds[1],18:p.reeds[2],19:p.reeds[3],20:p.beams[0],21:p.beams[1],22:p.beams[2],26:p.beams[3],27:p.door};if(g in ins)v=ins[g]?'LOW':'HIGH';if(g===28)v=p.power?'HIGH':'LOW';return {...x,live:v,source:'SIMULATION'};});}
}
