import * as THREE from 'three';import {OrbitControls} from 'three/addons/controls/OrbitControls.js';import {ModelBuilder} from './ModelBuilder.js';
export class SceneManager {
 constructor(container,data,onPick){this.container=container;this.data=data;this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x0e1722);this.scene.fog=new THREE.Fog(0x0e1722,2500,6000);this.camera=new THREE.PerspectiveCamera(37,1,1,10000);this.renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.localClippingEnabled=true;this.renderer.setSize(container.clientWidth,container.clientHeight);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.55;container.append(this.renderer.domElement);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.dampingFactor=.07;this.controls.minDistance=150;this.controls.maxDistance=3400;this.scene.add(new THREE.HemisphereLight(0xd9eeff,0x293549,2.6));const l=new THREE.DirectionalLight(0xc4dbff,4);l.position.set(400,1100,700);this.scene.add(l);const rim=new THREE.DirectionalLight(0x829fff,3);rim.position.set(-800,500,-400);this.scene.add(rim);const warm=new THREE.DirectionalLight(0xffe2c1,1.2);warm.position.set(600,600,-100);this.scene.add(warm);const grid=new THREE.GridHelper(1600,32,0x33465b,0x1a2a3d);grid.position.y=-5;this.scene.add(grid);this.model=new ModelBuilder(this.scene,data);this.options={mode:'PRODUCTO',opacity:1,explode:0,path:false,serviceOpen:false,wires:'NONE',assemblyStep:22};this.selected=null;this.selectedWire=null;this.raycaster=new THREE.Raycaster();this.raycaster.params.Line.threshold=4;this.pointer=new THREE.Vector2();this.onPick=onPick;this.measurePoints=[];this.measureMode=false;this.resetCamera();this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(container);let down=null;this.renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);this.renderer.domElement.addEventListener('pointerup',e=>{if(down&&Math.hypot(e.clientX-down[0],e.clientY-down[1])<5)this.pick(e);});this.setMode('PRODUCTO');}
 resetCamera(){this.camera.position.set(1000,950,1250);this.controls.target.set(0,420,0);this.controls.update();}
 resize(){const w=this.container.clientWidth,h=this.container.clientHeight;if(!w||!h)return;this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h);}
 setView(id){const V={V02:[0,430,1500],V03:[1600,430,0],V04:[-1600,430,0],V05:[0,450,-1550],V06:[0,2000,1],V07:[0,-1400,1],V10:[0,1600,1]};this.setMode(this.data.views.find(v=>v.id===id)?.mode??'PRODUCTO');if(V[id]){this.camera.position.set(...V[id]);this.controls.target.set(0,420,0);this.controls.update();}else this.resetCamera();if(id==='V08')this.options.serviceOpen=true;if(id==='V12')this.options.explode=.7;}
 setMode(mode){this.options.mode=mode;this.options.explode=mode==='EXPLODED'?.6:0;this.options.opacity=['PRODUCTO'].includes(mode)?1:.1;this.options.wires=['CABLEADO','SEÑALES'].includes(mode)?mode==='SEÑALES'?'SIGNAL ONLY':'ALL':'NONE';this.options.path=mode==='SIMULACIÓN';this.options.serviceOpen=['INTERIOR','MANTENIMIENTO','ENSAMBLAJE'].includes(mode);this.renderer.clippingPlanes=mode==='CORTE_L'?[new THREE.Plane(new THREE.Vector3(-1,0,0),0)]:mode==='CORTE_T'?[new THREE.Plane(new THREE.Vector3(0,-1,0),505)]:[];}
 selectComponent(id,focus=false){this.selected=id;this.selectedWire=null;const g=this.model.nodes.get(id);if(focus&&g){const box=new THREE.Box3().setFromObject(g);const target=box.getCenter(new THREE.Vector3());this.controls.target.copy(target);const size=Math.max(180,box.getSize(new THREE.Vector3()).length()*1.8);this.camera.position.copy(target).add(new THREE.Vector3(size*.75,size*.6,size));}return !!g;}
 selectWire(id){this.selectedWire=id;this.options.wires='ALL';this.options.opacity=.08;}
 pick(e){const r=this.renderer.domElement.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.raycaster.setFromCamera(this.pointer,this.camera);const hits=this.raycaster.intersectObject(this.model.root,true).filter(h=>{let n=h.object;while(n){if(!n.visible)return false;n=n.parent;}return true;});const hit=hits.find(h=>h.object.userData.wireId)||hits[0];if(!hit)return;if(this.measureMode){this.measurePoints.push(hit.point.clone());if(this.measurePoints.length===2){const distance=this.measurePoints[0].distanceTo(this.measurePoints[1]);this.onPick({measurement_mm:distance,points:this.measurePoints.map(p=>p.toArray()),status:'REFERENCE'});this.measurePoints=[];}return;}let n=hit.object;while(n&&!n.userData.componentId&&!n.userData.wireId)n=n.parent;if(n?.userData.wireId){this.selectWire(n.userData.wireId);this.onPick({wireId:n.userData.wireId});}else if(n?.userData.componentId){this.selectComponent(n.userData.componentId);this.onPick({componentId:n.userData.componentId});}}
 render(twin){const o=this.options,m=this.model;m.explode(o.explode);m.update(twin,o);const only={MECÁNICA:['MECHANICAL','ACTUATOR','SENSOR'],ELECTRÓNICA:['ELECTRONICS','WIRING'],INSPECCIÓN:['G','H','I','J'],ROTOR:['D','E','F'],DEPÓSITOS:['C','K']};for(const [id,g] of m.nodes){const a=g.userData.assembly,sys=g.userData.system,cab=sys==='CABINET';let visible=true;if(only[o.mode])visible=only[o.mode].includes(sys)||only[o.mode].includes(a);if(o.mode==='ENSAMBLAJE'){const c=this.data.components.find(c=>c.component_id===id);const step=this.data.groups.find(x=>x.id===a)?.assembly_step??22;visible=step<=o.assemblyStep;if(c?.number===65&&a==='B'&&o.assemblyStep<16)visible=false;}g.visible=visible;const related=this.selected&&this.data.wiring.some(w=>(w.from_component===this.selected&&w.to_component===id)||(w.to_component===this.selected&&w.from_component===id));g.traverse(child=>{if(!child.material||child.userData.wireId)return;const mats=Array.isArray(child.material)?child.material:[child.material];for(const mat of mats){if(mat.emissive&&!g.userData.lamp)mat.emissive.setHex(id===this.selected?0x286d8a:related?0x152e43:0);if(cab){mat.transparent=o.opacity<1;mat.opacity=o.opacity;mat.depthWrite=o.opacity>=.95;}else if(['CABLEADO','SEÑALES'].includes(o.mode)&&sys==='MECHANICAL'){mat.transparent=true;mat.opacity=.15;mat.depthWrite=false;}else if(child.geometry?.type!=='PlaneGeometry'&&id!=='SAFE-78'&&!id.startsWith('SENS-2')){mat.transparent=false;mat.opacity=1;mat.depthWrite=true;}}});}
  m.updateWires();for(const line of m.wireLines){const w=line.userData.wire;const f=o.wires;line.visible=f!=='NONE'&&(f==='ALL'||f==='POWER ONLY'&&['POWER','ACTUATORS'].includes(w.kind)||f==='SIGNAL ONLY'&&!['POWER','ACTUATORS'].includes(w.kind)||f==='SENSOR BUS'&&['I2C','SENSOR BUS'].includes(w.kind)||f==='I2C'&&w.kind==='I2C'||f==='ACTUATORS'&&['ACTUATORS','POWER'].includes(w.kind));if(this.selectedWire)line.material.opacity=line.userData.wireId===this.selectedWire?1:.12;else line.material.opacity=['POWER','ACTUATORS'].includes(w.kind)&&w.voltage.includes('switched')&&!twin.plant.power?.valueOf()?.valueOf()? .2:.8;line.material.transparent=true;}
  this.controls.update();this.renderer.render(this.scene,this.camera);
 }
 rebuild(){this.model.dispose();this.model=new ModelBuilder(this.scene,this.data);}
 screenshot(){return this.renderer.domElement.toDataURL('image/png');}
}
